/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as ProblemsRouteImport } from './routes/problems'
import { Route as ContestsRouteImport } from './routes/contests'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as R500RouteImport } from './routes/500'
import { Route as R404RouteImport } from './routes/404'
import { Route as R403RouteImport } from './routes/403'
import { Route as R401RouteImport } from './routes/401'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProblemsIndexRouteImport } from './routes/problems/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as UserSubmissionsRouteImport } from './routes/user/submissions'
import { Route as UserRegisterRouteImport } from './routes/user/register'
import { Route as UserProfileRouteImport } from './routes/user/profile'
import { Route as UserLoginRouteImport } from './routes/user/login'
import { Route as SubmissionsSubmissionIdRouteImport } from './routes/submissions/$submissionId'
import { Route as ProblemsQuestionIdRouteImport } from './routes/problems/$questionId'
import { Route as FooterTermsRouteImport } from './routes/footer/terms'
import { Route as FooterPrivacyRouteImport } from './routes/footer/privacy'
import { Route as FooterFeedbackRouteImport } from './routes/footer/feedback'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminQuestionsRouteImport } from './routes/admin/questions'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminQuestionsIndexRouteImport } from './routes/admin/questions/index'
import { Route as AdminQuestionsNewRouteImport } from './routes/admin/questions/new'
import { Route as AdminQuestionsQuestionIdEditRouteImport } from './routes/admin/questions/$questionId/edit'

const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsRoute = ProblemsRouteImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => rootRouteImport,
} as any)
const ContestsRoute = ContestsRouteImport.update({
  id: '/contests',
  path: '/contests',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const R500Route = R500RouteImport.update({
  id: '/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const R401Route = R401RouteImport.update({
  id: '/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsIndexRoute = ProblemsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProblemsRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const UserSubmissionsRoute = UserSubmissionsRouteImport.update({
  id: '/user/submissions',
  path: '/user/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRegisterRoute = UserRegisterRouteImport.update({
  id: '/user/register',
  path: '/user/register',
  getParentRoute: () => rootRouteImport,
} as any)
const UserProfileRoute = UserProfileRouteImport.update({
  id: '/user/profile',
  path: '/user/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const UserLoginRoute = UserLoginRouteImport.update({
  id: '/user/login',
  path: '/user/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionsSubmissionIdRoute = SubmissionsSubmissionIdRouteImport.update({
  id: '/submissions/$submissionId',
  path: '/submissions/$submissionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsQuestionIdRoute = ProblemsQuestionIdRouteImport.update({
  id: '/$questionId',
  path: '/$questionId',
  getParentRoute: () => ProblemsRoute,
} as any)
const FooterTermsRoute = FooterTermsRouteImport.update({
  id: '/footer/terms',
  path: '/footer/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const FooterPrivacyRoute = FooterPrivacyRouteImport.update({
  id: '/footer/privacy',
  path: '/footer/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const FooterFeedbackRoute = FooterFeedbackRouteImport.update({
  id: '/footer/feedback',
  path: '/footer/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuestionsRoute = AdminQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminQuestionsIndexRoute = AdminQuestionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminQuestionsRoute,
} as any)
const AdminQuestionsNewRoute = AdminQuestionsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminQuestionsRoute,
} as any)
const AdminQuestionsQuestionIdEditRoute =
  AdminQuestionsQuestionIdEditRouteImport.update({
    id: '/$questionId/edit',
    path: '/$questionId/edit',
    getParentRoute: () => AdminQuestionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/401': typeof R401Route
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/500': typeof R500Route
  '/admin': typeof AdminRouteWithChildren
  '/contests': typeof ContestsRoute
  '/problems': typeof ProblemsRouteWithChildren
  '/rankings': typeof RankingsRoute
  '/admin/questions': typeof AdminQuestionsRouteWithChildren
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/footer/feedback': typeof FooterFeedbackRoute
  '/footer/privacy': typeof FooterPrivacyRoute
  '/footer/terms': typeof FooterTermsRoute
  '/problems/$questionId': typeof ProblemsQuestionIdRoute
  '/submissions/$submissionId': typeof SubmissionsSubmissionIdRoute
  '/user/login': typeof UserLoginRoute
  '/user/profile': typeof UserProfileRoute
  '/user/register': typeof UserRegisterRoute
  '/user/submissions': typeof UserSubmissionsRoute
  '/admin/': typeof AdminIndexRoute
  '/problems/': typeof ProblemsIndexRoute
  '/admin/questions/new': typeof AdminQuestionsNewRoute
  '/admin/questions/': typeof AdminQuestionsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/questions/$questionId/edit': typeof AdminQuestionsQuestionIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/401': typeof R401Route
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/500': typeof R500Route
  '/contests': typeof ContestsRoute
  '/rankings': typeof RankingsRoute
  '/footer/feedback': typeof FooterFeedbackRoute
  '/footer/privacy': typeof FooterPrivacyRoute
  '/footer/terms': typeof FooterTermsRoute
  '/problems/$questionId': typeof ProblemsQuestionIdRoute
  '/submissions/$submissionId': typeof SubmissionsSubmissionIdRoute
  '/user/login': typeof UserLoginRoute
  '/user/profile': typeof UserProfileRoute
  '/user/register': typeof UserRegisterRoute
  '/user/submissions': typeof UserSubmissionsRoute
  '/admin': typeof AdminIndexRoute
  '/problems': typeof ProblemsIndexRoute
  '/admin/questions/new': typeof AdminQuestionsNewRoute
  '/admin/questions': typeof AdminQuestionsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/questions/$questionId/edit': typeof AdminQuestionsQuestionIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/401': typeof R401Route
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/500': typeof R500Route
  '/admin': typeof AdminRouteWithChildren
  '/contests': typeof ContestsRoute
  '/problems': typeof ProblemsRouteWithChildren
  '/rankings': typeof RankingsRoute
  '/admin/questions': typeof AdminQuestionsRouteWithChildren
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/footer/feedback': typeof FooterFeedbackRoute
  '/footer/privacy': typeof FooterPrivacyRoute
  '/footer/terms': typeof FooterTermsRoute
  '/problems/$questionId': typeof ProblemsQuestionIdRoute
  '/submissions/$submissionId': typeof SubmissionsSubmissionIdRoute
  '/user/login': typeof UserLoginRoute
  '/user/profile': typeof UserProfileRoute
  '/user/register': typeof UserRegisterRoute
  '/user/submissions': typeof UserSubmissionsRoute
  '/admin/': typeof AdminIndexRoute
  '/problems/': typeof ProblemsIndexRoute
  '/admin/questions/new': typeof AdminQuestionsNewRoute
  '/admin/questions/': typeof AdminQuestionsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/questions/$questionId/edit': typeof AdminQuestionsQuestionIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/admin'
    | '/contests'
    | '/problems'
    | '/rankings'
    | '/admin/questions'
    | '/admin/users'
    | '/footer/feedback'
    | '/footer/privacy'
    | '/footer/terms'
    | '/problems/$questionId'
    | '/submissions/$submissionId'
    | '/user/login'
    | '/user/profile'
    | '/user/register'
    | '/user/submissions'
    | '/admin/'
    | '/problems/'
    | '/admin/questions/new'
    | '/admin/questions/'
    | '/admin/users/'
    | '/admin/questions/$questionId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/contests'
    | '/rankings'
    | '/footer/feedback'
    | '/footer/privacy'
    | '/footer/terms'
    | '/problems/$questionId'
    | '/submissions/$submissionId'
    | '/user/login'
    | '/user/profile'
    | '/user/register'
    | '/user/submissions'
    | '/admin'
    | '/problems'
    | '/admin/questions/new'
    | '/admin/questions'
    | '/admin/users'
    | '/admin/questions/$questionId/edit'
  id:
    | '__root__'
    | '/'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/admin'
    | '/contests'
    | '/problems'
    | '/rankings'
    | '/admin/questions'
    | '/admin/users'
    | '/footer/feedback'
    | '/footer/privacy'
    | '/footer/terms'
    | '/problems/$questionId'
    | '/submissions/$submissionId'
    | '/user/login'
    | '/user/profile'
    | '/user/register'
    | '/user/submissions'
    | '/admin/'
    | '/problems/'
    | '/admin/questions/new'
    | '/admin/questions/'
    | '/admin/users/'
    | '/admin/questions/$questionId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R401Route: typeof R401Route
  R403Route: typeof R403Route
  R404Route: typeof R404Route
  R500Route: typeof R500Route
  AdminRoute: typeof AdminRouteWithChildren
  ContestsRoute: typeof ContestsRoute
  ProblemsRoute: typeof ProblemsRouteWithChildren
  RankingsRoute: typeof RankingsRoute
  FooterFeedbackRoute: typeof FooterFeedbackRoute
  FooterPrivacyRoute: typeof FooterPrivacyRoute
  FooterTermsRoute: typeof FooterTermsRoute
  SubmissionsSubmissionIdRoute: typeof SubmissionsSubmissionIdRoute
  UserLoginRoute: typeof UserLoginRoute
  UserProfileRoute: typeof UserProfileRoute
  UserRegisterRoute: typeof UserRegisterRoute
  UserSubmissionsRoute: typeof UserSubmissionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems': {
      id: '/problems'
      path: '/problems'
      fullPath: '/problems'
      preLoaderRoute: typeof ProblemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contests': {
      id: '/contests'
      path: '/contests'
      fullPath: '/contests'
      preLoaderRoute: typeof ContestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/500': {
      id: '/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof R500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/401': {
      id: '/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof R401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems/': {
      id: '/problems/'
      path: '/'
      fullPath: '/problems/'
      preLoaderRoute: typeof ProblemsIndexRouteImport
      parentRoute: typeof ProblemsRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/user/submissions': {
      id: '/user/submissions'
      path: '/user/submissions'
      fullPath: '/user/submissions'
      preLoaderRoute: typeof UserSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/register': {
      id: '/user/register'
      path: '/user/register'
      fullPath: '/user/register'
      preLoaderRoute: typeof UserRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/profile': {
      id: '/user/profile'
      path: '/user/profile'
      fullPath: '/user/profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/login': {
      id: '/user/login'
      path: '/user/login'
      fullPath: '/user/login'
      preLoaderRoute: typeof UserLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submissions/$submissionId': {
      id: '/submissions/$submissionId'
      path: '/submissions/$submissionId'
      fullPath: '/submissions/$submissionId'
      preLoaderRoute: typeof SubmissionsSubmissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems/$questionId': {
      id: '/problems/$questionId'
      path: '/$questionId'
      fullPath: '/problems/$questionId'
      preLoaderRoute: typeof ProblemsQuestionIdRouteImport
      parentRoute: typeof ProblemsRoute
    }
    '/footer/terms': {
      id: '/footer/terms'
      path: '/footer/terms'
      fullPath: '/footer/terms'
      preLoaderRoute: typeof FooterTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/footer/privacy': {
      id: '/footer/privacy'
      path: '/footer/privacy'
      fullPath: '/footer/privacy'
      preLoaderRoute: typeof FooterPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/footer/feedback': {
      id: '/footer/feedback'
      path: '/footer/feedback'
      fullPath: '/footer/feedback'
      preLoaderRoute: typeof FooterFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/questions': {
      id: '/admin/questions'
      path: '/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AdminQuestionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/questions/': {
      id: '/admin/questions/'
      path: '/'
      fullPath: '/admin/questions/'
      preLoaderRoute: typeof AdminQuestionsIndexRouteImport
      parentRoute: typeof AdminQuestionsRoute
    }
    '/admin/questions/new': {
      id: '/admin/questions/new'
      path: '/new'
      fullPath: '/admin/questions/new'
      preLoaderRoute: typeof AdminQuestionsNewRouteImport
      parentRoute: typeof AdminQuestionsRoute
    }
    '/admin/questions/$questionId/edit': {
      id: '/admin/questions/$questionId/edit'
      path: '/$questionId/edit'
      fullPath: '/admin/questions/$questionId/edit'
      preLoaderRoute: typeof AdminQuestionsQuestionIdEditRouteImport
      parentRoute: typeof AdminQuestionsRoute
    }
  }
}

interface AdminQuestionsRouteChildren {
  AdminQuestionsNewRoute: typeof AdminQuestionsNewRoute
  AdminQuestionsIndexRoute: typeof AdminQuestionsIndexRoute
  AdminQuestionsQuestionIdEditRoute: typeof AdminQuestionsQuestionIdEditRoute
}

const AdminQuestionsRouteChildren: AdminQuestionsRouteChildren = {
  AdminQuestionsNewRoute: AdminQuestionsNewRoute,
  AdminQuestionsIndexRoute: AdminQuestionsIndexRoute,
  AdminQuestionsQuestionIdEditRoute: AdminQuestionsQuestionIdEditRoute,
}

const AdminQuestionsRouteWithChildren = AdminQuestionsRoute._addFileChildren(
  AdminQuestionsRouteChildren,
)

interface AdminUsersRouteChildren {
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminRouteChildren {
  AdminQuestionsRoute: typeof AdminQuestionsRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminQuestionsRoute: AdminQuestionsRouteWithChildren,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ProblemsRouteChildren {
  ProblemsQuestionIdRoute: typeof ProblemsQuestionIdRoute
  ProblemsIndexRoute: typeof ProblemsIndexRoute
}

const ProblemsRouteChildren: ProblemsRouteChildren = {
  ProblemsQuestionIdRoute: ProblemsQuestionIdRoute,
  ProblemsIndexRoute: ProblemsIndexRoute,
}

const ProblemsRouteWithChildren = ProblemsRoute._addFileChildren(
  ProblemsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R401Route: R401Route,
  R403Route: R403Route,
  R404Route: R404Route,
  R500Route: R500Route,
  AdminRoute: AdminRouteWithChildren,
  ContestsRoute: ContestsRoute,
  ProblemsRoute: ProblemsRouteWithChildren,
  RankingsRoute: RankingsRoute,
  FooterFeedbackRoute: FooterFeedbackRoute,
  FooterPrivacyRoute: FooterPrivacyRoute,
  FooterTermsRoute: FooterTermsRoute,
  SubmissionsSubmissionIdRoute: SubmissionsSubmissionIdRoute,
  UserLoginRoute: UserLoginRoute,
  UserProfileRoute: UserProfileRoute,
  UserRegisterRoute: UserRegisterRoute,
  UserSubmissionsRoute: UserSubmissionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
