// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from 'O:/repo-java/oj/uc-frontend/myapp/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import CrownOutlined from 'O:/repo-java/oj/uc-frontend/myapp/node_modules/@ant-design/icons/es/icons/CrownOutlined';
import TableOutlined from 'O:/repo-java/oj/uc-frontend/myapp/node_modules/@ant-design/icons/es/icons/TableOutlined';
export default { SmileOutlined, CrownOutlined, TableOutlined };
